### ISSUE TITLE
Multiple setQueryParam calls do not work

### ISSUE THREAD

**Issue by ruudandriessen** [pbeshai/use-query-params#233]
Similar to `useState` hook - I expect every `set` call to take into account the existing search params.

Repro case:
https://codesandbox.io/s/patient-fire-fqnjt2?file=/src/App.js:0-787

Expected:
* After clicking the button, I expect the search params to be `foo=a&bar=b`.

Actual behaviour:
* After clicking the button, search params are set to `bar=b`. The `setFoo('a')` call not applied.

**Comment by hanserikb** [comment]
I'm having the same issue. While it fixes the issue if `{ options: { enableBatching: true}}` is added to the `QueryParamProvider`, i would still like it to work like pre v2 without the prop, so that it updates the state as many times as the setter is called and appends the query parameters properly.

**Comment by pbeshai** [comment]
This should be fixed in v2.0.1. Let me know if you have any further issues

**Comment by JulienDemarque** [comment]
> This should be fixed in v2.0.1. Let me know if you have any further issues

I am using  "use-query-params": "^2.1.1", and   "next-query-params": "^4.0.0", and it seems this is still happening. { enableBatching: true} solves it though.

**Comment by guoyunhe** [comment]
I am still having this issue with 2.1.2. (React Router 6)

**Comment by pbeshai** [comment]
It seems at some point the navigator returned by React Router stopped including location (maybe in 6.6? I haven't investigated). That breaks [this line in the adapter](https://github.com/pbeshai/use-query-params/blob/master/packages/use-query-params-adapter-react-router-6/src/index.ts#L38). I suggest either turning on batching in the useQueryParams options (enableBatching: true) or you could try changing that line in the adapter to just use `window.location` as the return value, but I haven't tested that as a fix.
