### ISSUE TITLE
Calling `setQueryParam` inside `useEffect` prevents location change when using React Router

### ISSUE THREAD

**Issue by evrimfeyyaz** [pbeshai/use-query-params#95]
As far as I can tell, there is no way to automatically append the parameters to the location on page load. For example, take the code below:

```js
const [country, setCountry] = useQueryParam(
  "country",
  withDefault(StringParam, "USA")
);
```

Here, `country` will have the default value of `"USA"`, but the location won't show `?country=USA`. This is not optimal behavior in my opinion, because defaults might change. Imagine your user views `https://example.com` and sees the information for the USA. Then shares this URL with others. And then, you change the default country to Turkey. Now the address `https://example.com` has a different meaning.

What I used to do was to automatically set these values within a `useEffect` hook:

```js
useEffect(() => {
  setCountry(country);
}, [])
```

This way, I was making sure that all the query parameters were there at all times.

With the new version of the library, this is no longer possible. I prepared a CodeSandbox playground to showcase this: https://codesandbox.io/s/react-playground-3e23x?file=/index.js:736-827

If you click on `Go to the second page`, you will see that it doesn't work, but a `?param=10` is appended to the location.

I did investigate a bit, and it seems that the culprit is the following code in `LocationProvider.tsx`:

```ts
const locationRef = React.useRef(location);
React.useEffect(() => {
  locationRef.current = location;
}, [location]);

const getLocation = React.useCallback(() => locationRef.current, [
  locationRef,
]);

const setLocation = React.useCallback(
  (queryReplacements: EncodedQuery, updateType?: UrlUpdateType) => {
    // A ref is needed here to stop setLocation updating constantly (see #46)

    // Here, `locationRef.current` is stale. It is updated in the
    // above `useEffect` hook after this call happens.
    locationRef.current = createLocationWithChanges(
      queryReplacements,
      locationRef.current,
      updateType,
      stringifyOptions
    );
    if (history) {
      updateUrlQuery(history, locationRef.current, updateType);
    }
  },
  [history, stringifyOptions]
);
```

Any suggestions on how to handle this issue? Is there an alternative way to make sure all query parameters are present at all times?

**Comment by pbeshai** [comment]
Your useEffect code makes sense to me, looks like it's a bug!

**Comment by pbeshai** [comment]
Fixed in 1.1.2

**Comment by evrimfeyyaz** [comment]
@pbeshai Thanks a lot for the quick response and fix Peter.

I would say, using query parameters that are always present is still not very straightforward. I created a custom hook for this for the moment:

```ts
import { QueryParamConfig } from 'serialize-query-params';
import { useQueryParam } from 'use-query-params';
import { useEffect } from 'react';

declare type NewValueType<D> = D | ((latestValue: D) => D);

export function useAlwaysPresentQueryParam<D>(
  name: string,
  defaultValue: NonNullable<D>,
  paramConfig?: QueryParamConfig<D>,
): [
  NonNullable<D>,
  (newValue: NewValueType<D>, updateType?: 'replace' | 'push' | 'replaceIn' | 'pushIn' | undefined) => void
] {
  const [queryParam, setQueryParam] = useQueryParam(name, paramConfig);

  useEffect(() => {
    if (queryParam == null) {
      setQueryParam(defaultValue);
    }
  }, [queryParam, setQueryParam, defaultValue]);

  return [queryParam ?? defaultValue, setQueryParam];
}
```

Would you be interested in including something like this in the library? If you are, I might be able to send a pull request for this in the next few weeks when I have time.

**Comment by pbeshai** [comment]
I think with the latest changes of allowing null working with default values becomes more annoying and can probably use some deeper thinking on making better. As for the always present default value idea, I think there's merit there, but I'm okay with leaving it in userland for now. Perhaps in the future it can be a global option if we change the way defaults are configured... otherwise, people can steal your hook above for those that want it :) 

Also, btw you probably want to switch to using `replaceIn` instead of `pushIn` (the default) for this sort of operation to prevent adding a new entry on the history stack.

**Comment by evrimfeyyaz** [comment]
@pbeshai Sounds good Peter.

And I have also just noticed that there was an extra entry being pushed into the browser history with my hook, and was about to post a comment about it :) I have changed the code above to use `replaceIn` as you recommended.

**Comment by nichita-pasecinic** [comment]
Hi @pbeshai , thanks for this amazing library!

About the question with default query params (to be shown in the browser search bar at first render)
Is the hook above a recemented solution ? Why it isn't yet a global flag that allows to `syncDefault` ? (same as `recoil-sync`) with state & query param, as it is a very common request
